# Generated by Django 4.2.10 on 2025-11-18 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=200)),
                ('identification_number', models.CharField(max_length=50)),
                ('diagnosis_date', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.CharField(max_length=100)),
                ('risk_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('probabilities', models.JSONField()),
                ('image_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diagnostics_diagnostichistory',
                'ordering': ['-diagnosis_date'],
            },
        ),
    ]
